// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { userEvent } from '@testing-library/user-event';
import { act } from '@testing-library/react';
import { createRef, useRef } from 'react';
import { afterEach, expect, it, vi } from 'vitest';
import { ToastProvider, Tooltip, useToast } from '../src/react/index.js';
afterEach(()=>{cleanup();vi.useRealTimers()});
globalThis.ResizeObserver ??= class { observe(){} unobserve(){} disconnect(){} };
function Harness(){ const { toast }=useToast(); return <button onClick={()=>{toast({title:'First'});toast({title:'Second'})}}>Notify</button> }
it('queues and removes accessible toasts', async()=>{ const user=userEvent.setup(); render(<ToastProvider><Harness/></ToastProvider>); await user.click(screen.getByRole('button',{name:'Notify'})); expect(screen.getAllByRole('status')).toHaveLength(2); const dismiss=screen.getAllByRole('button',{name:'Dismiss notification'}).at(0); expect(dismiss).toBeDefined(); if(dismiss) await user.click(dismiss); expect(screen.getAllByRole('status')).toHaveLength(1); });
it('auto-dismisses provider-owned toasts after the configured duration', async()=>{vi.useFakeTimers();render(<ToastProvider duration={3000}><Harness/></ToastProvider>);act(()=>fireEvent.click(screen.getByRole('button',{name:'Notify'})));expect(screen.getAllByRole('status')).toHaveLength(2);act(()=>vi.advanceTimersByTime(2999));expect(screen.getAllByRole('status')).toHaveLength(2);act(()=>vi.advanceTimersByTime(1));expect(screen.queryAllByRole('status')).toHaveLength(0);});
it('keeps each auto-dismiss deadline stable while later toasts enter and leave the queue',()=>{vi.useFakeTimers();function QueueHarness(){const {toast,dismiss}=useToast();const laterId=useRef<number|undefined>(undefined);return <><button onClick={()=>toast({title:'Original'})}>Add original</button><button onClick={()=>{laterId.current=toast({title:'Later',duration:10000})}}>Add later</button><button onClick={()=>{if(laterId.current!==undefined)dismiss(laterId.current)}}>Remove later</button></>}render(<ToastProvider duration={3000}><QueueHarness/></ToastProvider>);act(()=>fireEvent.click(screen.getByRole('button',{name:'Add original'})));act(()=>vi.advanceTimersByTime(1000));act(()=>fireEvent.click(screen.getByRole('button',{name:'Add later'})));act(()=>vi.advanceTimersByTime(500));act(()=>fireEvent.click(screen.getByRole('button',{name:'Remove later'})));act(()=>vi.advanceTimersByTime(1499));expect(screen.getByText('Original')).toBeInTheDocument();act(()=>vi.advanceTimersByTime(1));expect(screen.queryByText('Original')).not.toBeInTheDocument();});
it('forwards a typed ref and DOM props to the toast viewport',()=>{const ref=createRef<HTMLDivElement>();render(<ToastProvider ref={ref} viewportProps={{'data-testid':'viewport'}}><span>Child</span></ToastProvider>);expect(ref.current).toBe(screen.getByTestId('viewport'));});
it('supports controlled tooltip state and forwards content DOM props',()=>{const change=vi.fn();render(<Tooltip content="Helpful" open onOpenChange={change} contentProps={{'data-testid':'tip'}}><button>Help</button></Tooltip>);expect(screen.getByTestId('tip')).toBeInTheDocument();expect(screen.getByRole('tooltip')).toHaveTextContent('Helpful');});
it('shows a tooltip for a labelled trigger', async()=>{ const user=userEvent.setup(); render(<Tooltip content="Helpful"><button>Help</button></Tooltip>); await user.hover(screen.getByRole('button',{name:'Help'})); expect(await screen.findByRole('tooltip')).toHaveTextContent('Helpful'); });
