import * as DialogPrimitive from '@radix-ui/react-dialog';
import * as MenuPrimitive from '@radix-ui/react-dropdown-menu';
import { clsx } from 'clsx';
import type { ReactElement, ReactNode } from 'react';
export interface DialogProps {trigger?:ReactElement;title:string;description?:string;children:ReactNode;open?:boolean;defaultOpen?:boolean;onOpenChange?:(open:boolean)=>void;className?:string}
export function Dialog({trigger,title,description,children,open,defaultOpen,onOpenChange,className}:DialogProps){const rootProps={...(open!==undefined?{open}:{}),...(defaultOpen!==undefined?{defaultOpen}:{}),...(onOpenChange?{onOpenChange}:{})};return <DialogPrimitive.Root {...rootProps}>{trigger&&<DialogPrimitive.Trigger asChild>{trigger}</DialogPrimitive.Trigger>}<DialogPrimitive.Portal><DialogPrimitive.Overlay className="sewak-dialog-overlay"/><DialogPrimitive.Content className={clsx('sewak-dialog',className)}><DialogPrimitive.Title className="sewak-dialog__title">{title}</DialogPrimitive.Title>{description&&<DialogPrimitive.Description className="sewak-dialog__description">{description}</DialogPrimitive.Description>}<div className="sewak-dialog__body">{children}</div><DialogPrimitive.Close className="sewak-dialog__close" aria-label="Close dialog">×</DialogPrimitive.Close></DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>}
export interface ConfirmDialogProps extends Omit<DialogProps,'children'>{confirmLabel?:string;cancelLabel?:string;onConfirm:()=>void;danger?:boolean}
export function ConfirmDialog({confirmLabel='Confirm',cancelLabel='Cancel',onConfirm,danger,...props}:ConfirmDialogProps){return <Dialog {...props}><div className="sewak-dialog__actions"><DialogPrimitive.Close asChild><button type="button" className="sewak-button sewak-button--secondary">{cancelLabel}</button></DialogPrimitive.Close><DialogPrimitive.Close asChild><button type="button" className={clsx('sewak-button',danger?'sewak-button--danger':'sewak-button--primary')} onClick={onConfirm}>{confirmLabel}</button></DialogPrimitive.Close></div></Dialog>}
export interface MenuItem {label:string;onSelect:()=>void;disabled?:boolean}
export function DropdownMenu({trigger,items}:{trigger:ReactElement;items:MenuItem[]}){return <MenuPrimitive.Root><MenuPrimitive.Trigger asChild>{trigger}</MenuPrimitive.Trigger><MenuPrimitive.Portal><MenuPrimitive.Content className="sewak-menu" sideOffset={6}>{items.map(item=><MenuPrimitive.Item key={item.label} {...(item.disabled!==undefined?{disabled:item.disabled}:{})} onSelect={item.onSelect} className="sewak-menu__item">{item.label}</MenuPrimitive.Item>)}</MenuPrimitive.Content></MenuPrimitive.Portal></MenuPrimitive.Root>}
export interface DrawerProps extends DialogProps{side?:'left'|'right'}
export function Drawer({side='right',className,...props}:DrawerProps){return <Dialog {...props} className={clsx('sewak-drawer',`sewak-drawer--${side}`,className)}/>}
