import * as DialogPrimitive from '@radix-ui/react-dialog';
import * as MenuPrimitive from '@radix-ui/react-dropdown-menu';
import { clsx } from 'clsx';
import { forwardRef } from 'react';
import type { ComponentPropsWithoutRef, ElementRef, HTMLAttributes, ReactElement, ReactNode } from 'react';
export interface DialogProps extends Omit<ComponentPropsWithoutRef<typeof DialogPrimitive.Content>,'title'|'children'>{trigger?:ReactElement;title:string;description?:string;children:ReactNode;open?:boolean;defaultOpen?:boolean;onOpenChange?:(open:boolean)=>void}
export const Dialog=forwardRef<ElementRef<typeof DialogPrimitive.Content>,DialogProps>(function Dialog({trigger,title,description,children,open,defaultOpen,onOpenChange,className,...contentProps},ref){const rootProps={...(open!==undefined?{open}:{}),...(defaultOpen!==undefined?{defaultOpen}:{}),...(onOpenChange?{onOpenChange}:{})};return <DialogPrimitive.Root {...rootProps}>{trigger&&<DialogPrimitive.Trigger asChild>{trigger}</DialogPrimitive.Trigger>}<DialogPrimitive.Portal><DialogPrimitive.Overlay className="sewak-dialog-overlay"/><DialogPrimitive.Content {...contentProps} ref={ref} className={clsx('sewak-dialog',className)}><DialogPrimitive.Title className="sewak-dialog__title">{title}</DialogPrimitive.Title>{description&&<DialogPrimitive.Description className="sewak-dialog__description">{description}</DialogPrimitive.Description>}<div className="sewak-dialog__body">{children}</div><DialogPrimitive.Close className="sewak-dialog__close" aria-label="Close dialog">×</DialogPrimitive.Close></DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>});
export interface ConfirmDialogProps extends Omit<DialogProps,'children'>{confirmLabel?:string;cancelLabel?:string;onConfirm:()=>void;danger?:boolean}
export const ConfirmDialog=forwardRef<ElementRef<typeof DialogPrimitive.Content>,ConfirmDialogProps>(function ConfirmDialog({confirmLabel='Confirm',cancelLabel='Cancel',onConfirm,danger,...props},ref){return <Dialog {...props} ref={ref}><div className="sewak-dialog__actions"><DialogPrimitive.Close asChild><button type="button" className="sewak-button sewak-button--secondary">{cancelLabel}</button></DialogPrimitive.Close><DialogPrimitive.Close asChild><button type="button" className={clsx('sewak-button',danger?'sewak-button--danger':'sewak-button--primary')} onClick={onConfirm}>{confirmLabel}</button></DialogPrimitive.Close></div></Dialog>});
export interface MenuItem {label:string;onSelect:()=>void;disabled?:boolean}
type DataAttributes = { [key:`data-${string}`]: string|undefined };
export interface DropdownMenuProps {trigger:ReactElement;items:MenuItem[];open?:boolean;defaultOpen?:boolean;onOpenChange?:(open:boolean)=>void;contentProps?:(ComponentPropsWithoutRef<typeof MenuPrimitive.Content>&HTMLAttributes<HTMLDivElement>&DataAttributes)}
export const DropdownMenu=forwardRef<ElementRef<typeof MenuPrimitive.Content>,DropdownMenuProps>(function DropdownMenu({trigger,items,open,defaultOpen,onOpenChange,contentProps},ref){const rootProps={...(open!==undefined?{open}:{}),...(defaultOpen!==undefined?{defaultOpen}:{}),...(onOpenChange?{onOpenChange}:{})};return <MenuPrimitive.Root {...rootProps}><MenuPrimitive.Trigger asChild>{trigger}</MenuPrimitive.Trigger><MenuPrimitive.Portal><MenuPrimitive.Content {...contentProps} ref={ref} className={clsx('sewak-menu',contentProps?.className)} sideOffset={contentProps?.sideOffset??6}>{items.map(item=><MenuPrimitive.Item key={item.label} {...(item.disabled!==undefined?{disabled:item.disabled}:{})} onSelect={item.onSelect} className="sewak-menu__item">{item.label}</MenuPrimitive.Item>)}</MenuPrimitive.Content></MenuPrimitive.Portal></MenuPrimitive.Root>});
export interface DrawerProps extends DialogProps{side?:'left'|'right'}
export const Drawer=forwardRef<ElementRef<typeof DialogPrimitive.Content>,DrawerProps>(function Drawer({side='right',className,...props},ref){return <Dialog {...props} ref={ref} className={clsx('sewak-drawer',`sewak-drawer--${side}`,className)}/>});
